
const backlog = [
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C01",
    Title: "2x Antennas",
    Complexity: 1,
    Defense: 1,
    Supremacy: 1,
    Notes: "Common antennas for medium distance communication.<br>They are installed in two poles of the station to create a dipoles to maximize directionality of signals and cover wider distances.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "I04",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "yy",
    sfondo: "bg1"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C02",
    Title: "Hyperspace antenna",
    Complexity: 3,
    Defense: 1,
    Supremacy: 1,
    Notes: "A specific wide rhombus-shaped antenna to communicate through hyperspace.<br>Needed for galactic communications.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "I04",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "yy",
    sfondo: "bg2"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C03",
    Title: "Connector to network (Design)",
    Complexity: 3,
    Defense: 0,
    Supremacy: 0,
    Notes: "Design of interface to connect components to the network of the station. Designed for mass production.",
    LegoBuild: "Required by MODule activities to integrate in the communication channels. Design and build 1 but we need many.",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "C16",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "",
    sfondo: "bg3"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C04",
    Title: "Satellite communication system",
    Complexity: 5,
    Defense: 0,
    Supremacy: 0,
    Notes: "Special high frequency multi-band system to connect the station with satellites around the hosting planet. ",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "C01",
    Dep2: "C09",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "yy",
    sfondo: "bg4"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C05",
    Title: "30x Connectors to network",
    Complexity: 8,
    Defense: 0,
    Supremacy: 0,
    Notes: "Physical interfaces to connect each component to the network of the station.",
    LegoBuild: "Required by MODule activities to integrate  in the communication channels.",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "C03",
    Dep2: "I04",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "Int-com.png",
    Ctrl_num: 30,
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "",
    sfondo: "bg5"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C06",
    Title: "Video monitoring system",
    Complexity: 5,
    Defense: 1,
    Supremacy: 0,
    Notes: "Modular system to transmit video channel on the network. It is built on top of standard communication network using special broadcast P2P algorithms managed by high computational power.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "D08",
    Dep2: "C03",
    Dep3: "C15",
    DepInt1: "",
    DepInt2: "y",
    DepInt3: "y",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "yy",
    sfondo: "bg6"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C07",
    Title: "Automatic Recognition System",
    Complexity: 3,
    Defense: 2,
    Supremacy: 1,
    Notes: "ARS is connected to the video monitoring system to intercept all vireo recording of faces and codes of the people moving in the station. It is directly connected to main computing device to apply recognition algorithm.",
    LegoBuild: "Upgrade communication interface module Required by MODule to integrate video in communication interface. We need many",
    Liv: "",
    Com: "",
    Pwr: "y",
    Dec: "",
    Dep1: "C06",
    Dep2: "C09",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "y",
    sfondo: "bg7"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C08",
    Title: "50x Connectors to network",
    Complexity: 8,
    Defense: 0,
    Supremacy: 0,
    Notes: "Physical interfaces to connect each component to the network of the station.",
    LegoBuild: "Required by MODule activities to integrate  in the communication channels.",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "C03",
    Dep2: "I15",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "Int-com.png",
    Ctrl_num: 50,
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "",
    sfondo: "bg8"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C09",
    Title: "Cyberwarfare platform",
    Complexity: 5,
    Defense: 1,
    Supremacy: 1,
    Notes: "Dedicated set of large devices with High computational powerCOMMA focused on monitoring and decoding external communication frequencies.",
    LegoBuild: "To connect to planet explorer.",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "C01",
    Dep2: "C15",
    Dep3: "I03",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "yy",
    sfondo: "bg9"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C10",
    Title: "Teleport beam",
    Complexity: 5,
    Defense: 0,
    Supremacy: 0,
    Notes: "Special low energy bean to transport and re-construct physical objects in short range distanceCOMMA ideal to land on a planet from orbit without a shuttle.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "y",
    Dep1: "C02",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "yyyy",
    sfondo: "bg10"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C11",
    Title: "4x antennas",
    Complexity: 2,
    Defense: 2,
    Supremacy: 0,
    Notes: "Basic antennas system to communicate with station neighbours.<br>Installed on the other 2 directions of the 3 dimensions",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "C01",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "yy",
    sfondo: "bg11"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C12",
    Title: "Broadcasting Juggle Device",
    Complexity: 5,
    Defense: 1,
    Supremacy: 1,
    Notes: "System to intercept and juggle transmissions in the hosting planet",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "y",
    Dep1: "C09",
    Dep2: "I07",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "yyy",
    sfondo: "bg12"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C13",
    Title: "Hyperband network",
    Complexity: 5,
    Defense: 0,
    Supremacy: 0,
    Notes: "High speed network to connect all componentsCOMMA system and devices in the station.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "C16",
    Dep2: "I03",
    Dep3: "I04",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "yy",
    sfondo: "bg13"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C14",
    Title: "Memory data storage",
    Complexity: 2,
    Defense: 0,
    Supremacy: 0,
    Notes: "Red lighted room for keeping safe data in memory databank at low temperature.<br>Access protectionCOMMA fire protectionCOMMA redundant racks.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "y",
    Dep1: "I04",
    Dep2: "I03",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "yyy",
    sfondo: "bg14"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C15",
    Title: "XAL-9k supercomputer",
    Complexity: 13,
    Defense: 2,
    Supremacy: 2,
    Notes: "Supercomputer to manage computation for components of the station. Has red light cameras in different places and can interact with humans using a natural language interface.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "C13",
    Dep2: "C14",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "yy",
    sfondo: "bg15"
  },
  {
    NumCards: 1,
    Epic: "Communication",
    Card_ID: "C16",
    Title: "Network centre ",
    Complexity: 8,
    Defense: 1,
    Supremacy: 1,
    Notes: "Central room where all connections are centralized. <br> It is placed near the core of the station and is designed as a 3D shaped star to optimize connectivity in the 3 dimensions.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "C14",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ffff",
    "ini-logo": "C-logo.png",
    NeedInt: "yy",
    sfondo: "bg16"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D01",
    Title: "Lower command deck",
    Complexity: 13,
    Defense: 3,
    Supremacy: 0,
    Notes: "Command deck for all systems except the warfare one.<br>It has a central corridor with all officers with a bunch of screens on the walls.",
    LegoBuild: "For all systems except warfare.",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "yyy",
    sfondo: "bg1"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D02",
    Title: "Defence Shield System",
    Complexity: 8,
    Defense: 5,
    Supremacy: 0,
    Notes: "The core centre to manage the 8 shields that create the spherical anti-magnetic and anti-gravitational field force all around the station.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "y",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "yyy",
    sfondo: "bg2"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D03",
    Title: "Laser gun tower (Design)",
    Complexity: 3,
    Defense: 1,
    Supremacy: 0,
    Notes: "Design of a single tower equipped with 2 laser cannonsCOMMA placed on rotating and pointing base.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "",
    Dec: "y",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "yy",
    sfondo: "bg3"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D04",
    Title: "Surface corridor #1",
    Complexity: 2,
    Defense: 0,
    Supremacy: 0,
    Notes: "A corridor connecting exhausting tunnels to facilitate heat dispersion in the space from the core of the station.<br>It is protected with a line of laser gun towers.",
    LegoBuild: "Needs 5+5 laser gun towers to protect it.",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "",
    sfondo: "bg4"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D05",
    Title: "8x laser gun towers",
    Complexity: 5,
    Defense: 3,
    Supremacy: 1,
    Notes: "A line of 8 laser gun towers can work together to protect a line of attack.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "",
    Dec: "y",
    Dep1: "D03",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "yy",
    sfondo: "bg5"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D06",
    Title: "Hyperspace sensor",
    Complexity: 2,
    Defense: 3,
    Supremacy: 0,
    Notes: "A specific device that can read gravitational waves generated by objects moving in the hyperspace.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "y",
    Dep1: "I04",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "yyy",
    sfondo: "bg6"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D07",
    Title: "4x shields projectors",
    Complexity: 13,
    Defense: 5,
    Supremacy: 0,
    Notes: "Projectors for anti-magnetic and anti-gravitational field force to protect the station.<br>They are physically connected to DSS with dedicated high energy connections",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "y",
    Dep1: "D02",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "yyy",
    sfondo: "bg7"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D08",
    Title: "Security control room",
    Complexity: 5,
    Defense: 2,
    Supremacy: 0,
    Notes: "Control room to monitor and control all defence systems.<br>It is occupied 24/7 and each shift is composed by 4 operatorsCOMMA sat at their desksCOMMA with screens and leverages.<br>One bed is available for emergency shifts.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "C09",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "yyy",
    sfondo: "bg8"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D09",
    Title: "4x shields projectors",
    Complexity: 13,
    Defense: 5,
    Supremacy: 0,
    Notes: "Projectors for anti-magnetic and anti-gravitational field force to protect the station.<br>They are physically connected to DSS with dedicated high energy connections",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "y",
    Dep1: "D07",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "yyy",
    sfondo: "bg9"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D10",
    Title: "Troopers’ weapon storage ",
    Complexity: 1,
    Defense: 2,
    Supremacy: 2,
    Notes: "Room to keep all weapons for Space Troopers while they are not using them. Organised in 2 sections with a physical gate and a place for an officer to oversee all activities.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "yyy",
    sfondo: "bg10"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D11",
    Title: "Troopers’ training room",
    Complexity: 2,
    Defense: 2,
    Supremacy: 1,
    Notes: "A room to let troop train in short range body combat and long range hits.<br>There is a gym and a shooting range.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "yyy",
    sfondo: "bg11"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D12",
    Title: "Surface corridor #2",
    Complexity: 2,
    Defense: 0,
    Supremacy: 0,
    Notes: "A corridor connecting exhausting tunnels to facilitate heat dispersion in the space from the core of the station.<br>It is protected with a line of laser gun towers.",
    LegoBuild: "Needs 5+5 laser gun towers to protect it.",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "D04",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "",
    sfondo: "bg12"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D13",
    Title: "Surface corridor #3",
    Complexity: 2,
    Defense: 0,
    Supremacy: 0,
    Notes: "A corridor connecting exhausting tunnels to facilitate heat dispersion in the space from the core of the station.<br>It is protected with a line of laser gun towers.",
    LegoBuild: "Needs 5+5 laser gun towers to protect it.",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "D12",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "",
    sfondo: "bg13"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D14",
    Title: "8x laser gun towers",
    Complexity: 5,
    Defense: 3,
    Supremacy: 1,
    Notes: "A line of 8 laser gun towers can work together to protect a possible line of attack around the surface corridors of the station.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "",
    Dec: "y",
    Dep1: "D03",
    Dep2: "D12",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "yy",
    sfondo: "bg14"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D15",
    Title: "8x laser gun towers",
    Complexity: 5,
    Defense: 3,
    Supremacy: 1,
    Notes: "A line of 8 laser gun towers can work together to protect a possible line of attack around the surface corridors of the station.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "",
    Dec: "y",
    Dep1: "D03",
    Dep2: "D12",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "yy",
    sfondo: "bg15"
  },
  {
    NumCards: 1,
    Epic: "Defence",
    Card_ID: "D16",
    Title: "8x laser gun towers",
    Complexity: 5,
    Defense: 3,
    Supremacy: 1,
    Notes: "A line of 8 laser gun towers can work together to protect a possible line of attack around the surface corridors of the station.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "",
    Dec: "y",
    Dep1: "D03",
    Dep2: "D13",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#0000ff",
    "ini-logo": "D-logo.png",
    NeedInt: "yy",
    sfondo: "bg16"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I01",
    Title: "Antimatter reactor",
    Complexity: 13,
    Defense: 0,
    Supremacy: 0,
    Notes: "A small torus of rotating antimatterCOMMA completely isolated by the rest of the space to avoid annihilation process. <br>Antimatter at this status must be at 4 M Kelvin temperature in the full vacuum.",
    LegoBuild: "Main power generator",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "I02",
    Dep2: "I03",
    Dep3: "I05",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "y",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "yy",
    sfondo: "bg1"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I02",
    Title: "Magnetic insulator",
    Complexity: 8,
    Defense: 0,
    Supremacy: 0,
    Notes: "A magnetic insulator that keep antimatter in the middle of the toroidal camera to avoid melting of the containing system for the high temperature.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "",
    Dec: "y",
    Dep1: "I03",
    Dep2: "L04",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "yy",
    sfondo: "bg2"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I03",
    Title: "Cooler system",
    Complexity: 2,
    Defense: 0,
    Supremacy: 0,
    Notes: "The system to keep the temperature of the magnetic insulator under control.<br>It is directly connected to the exhausting tunnels to disperse heat in deep space.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "I01",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "yy",
    sfondo: "bg3"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I04",
    Title: "Control room",
    Complexity: 5,
    Defense: 2,
    Supremacy: 0,
    Notes: "Room to monitor all infrastructure systems. Have 3 desks with monitors and devices.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "I07",
    Dep2: "D10",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "yyy",
    sfondo: "bg4"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I05",
    Title: "10x High Energy connectors",
    Complexity: 3,
    Defense: 0,
    Supremacy: 0,
    Notes: "Physical interfaces to connect components to a P2D for high power usage.<br>Designed as evolution of standard power connectors.",
    LegoBuild: "",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "I10",
    Dep2: "I11",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "Int-hpwr.png",
    Ctrl_num: 10,
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "",
    sfondo: "bg5"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I06",
    Title: "P2D #1",
    Complexity: 5,
    Defense: 0,
    Supremacy: 0,
    Notes: "Power Decoupling Device is connected to main reactor and able to distribute energy to components.",
    LegoBuild: "Required by DECoupled activities to integrate decoupled power management interface. Can sustain 10 modules. ",
    Liv: "",
    Com: "y",
    Pwr: "",
    Dec: "",
    Dep1: "I01",
    Dep2: "I09",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "y",
    sfondo: "bg6"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I07",
    Title: "Upper command deck",
    Complexity: 5,
    Defense: 3,
    Supremacy: 3,
    Notes: "Room to monitor all warfare systems. Has 5 desks with monitors and devices.",
    LegoBuild: "For warfare systems",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "C09",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "yyy",
    sfondo: "bg7"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I08",
    Title: "Power exhausting tunnel #1",
    Complexity: 1,
    Defense: 0,
    Supremacy: 0,
    Notes: "Tunnel to connect the reactor with outer space to disperse heat in the space. Identical tunnels are built on the 3 axis of the station (from the core) and exit in the surface corridors.",
    LegoBuild: "we need 6",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "D04",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "",
    sfondo: "bg8"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I09",
    Title: "Amplifiers maintenance tunnel",
    Complexity: 3,
    Defense: 0,
    Supremacy: 0,
    Notes: "This large area is required to access to P2Ds aligned on the bridge that go through it.<br> This tunnel is directly connected to the reactor.",
    LegoBuild: "To access to decoupling powerstations and connected to reactor",
    Liv: "y",
    Com: "",
    Pwr: "y",
    Dec: "",
    Dep1: "I01",
    Dep2: "I04",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "yy",
    sfondo: "bg9"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I10",
    Title: "P2D #2",
    Complexity: 5,
    Defense: 0,
    Supremacy: 0,
    Notes: "Power Decoupling Device is connected to main reactor and able to distribute energy to components.",
    LegoBuild: "Required by DECoupled activities to integrate decoupled power management interface.Can sustain 10 modules.",
    Liv: "",
    Com: "y",
    Pwr: "",
    Dec: "",
    Dep1: "I01",
    Dep2: "I09",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "y",
    sfondo: "bg10"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I11",
    Title: "Connector to Power grid (Design)",
    Complexity: 2,
    Defense: 0,
    Supremacy: 0,
    Notes: "Design of the connectors to the power grid.<br>Designed for mass production.",
    LegoBuild: "Required by MODule activities to power the module. We need many. ",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "I01",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "",
    sfondo: "bg11"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I12",
    Title: "Maintenance pod",
    Complexity: 2,
    Defense: 1,
    Supremacy: 0,
    Notes: "Spherical vehicle with 2 arms to manipulate objects in the outer space and perform EVA (Extra Vehicle Activity).",
    LegoBuild: "Intraspace movements. Minifig scale",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "",
    sfondo: "bg12"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I13",
    Title: "10x High Energy connectors",
    Complexity: 3,
    Defense: 0,
    Supremacy: 0,
    Notes: "Physical interfaces to connect components to a P2D for high power usage.<br>Designed as evolution of standard power connectors.",
    LegoBuild: "",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "I19",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "Int-hpwr.png",
    Ctrl_num: 10,
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "",
    sfondo: "bg13"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I14",
    Title: "2x power exhausting tunnels",
    Complexity: 1,
    Defense: 0,
    Supremacy: 0,
    Notes: "Tunnels to connect the reactor with outer space to disperse heat in the space. Identical tunnels are built on the 3 axis of the station (from the core) and exit in the surface corridors.",
    LegoBuild: "",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "I08",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "",
    sfondo: "bg14"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I15",
    Title: "Secondary control room",
    Complexity: 3,
    Defense: 2,
    Supremacy: 0,
    Notes: "Emergency room to monitor all infrastructure systems. Have 2 desks with monitors and devices.<br>Must have same number of monitors and device than main control room.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "I04",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "yyy",
    sfondo: "bg15"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I16",
    Title: "20x  power grid connectors",
    Complexity: 3,
    Defense: 0,
    Supremacy: 0,
    Notes: "Physical interfaces to connect components to the standard power grid of the station distributed to low energy grid of P2D.",
    LegoBuild: "Required by MODule activities to power the module.",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "I04",
    Dep2: "I06",
    Dep3: "I11",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "y",
    Ctrl_type: "Int-lpwr.png",
    Ctrl_num: 20,
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "",
    sfondo: "bg16"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I17",
    Title: "10x High Energy connectors",
    Complexity: 3,
    Defense: 0,
    Supremacy: 0,
    Notes: "Physical interfaces to connect components to a P2D for high power usage.<br>Designed as evolution of standard power connectors.",
    LegoBuild: "Are manned minishuttle to repair external surface parts.",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "I06",
    Dep2: "I11",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "Int-hpwr.png",
    Ctrl_num: 10,
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "",
    sfondo: "bg17"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I18",
    Title: "3x power exhausting tunnels",
    Complexity: 3,
    Defense: 0,
    Supremacy: 0,
    Notes: "Tunnels to connect the reactor with outer space to disperse heat in the space. Identical tunnels are built on the 3 axis of the station (from the core) and exit in the surface corridors.",
    LegoBuild: "",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "I14",
    Dep2: "I15",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "",
    sfondo: "bg18"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I19",
    Title: "P2D  #3",
    Complexity: 3,
    Defense: 0,
    Supremacy: 0,
    Notes: "Power Decoupling Device is connected to main reactor and able to distribute energy to components.",
    LegoBuild: "Required by DECoupled activities to integrate decoupled power management interface. Can sustain 10 modules.",
    Liv: "",
    Com: "y",
    Pwr: "",
    Dec: "",
    Dep1: "I10",
    Dep2: "I15",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "y",
    sfondo: "bg19"
  },
  {
    NumCards: 1,
    Epic: "Infrastructure",
    Card_ID: "I20",
    Title: "50x  power grid connectors",
    Complexity: 5,
    Defense: 0,
    Supremacy: 0,
    Notes: "Physical interfaces to connect components to the standard power grid of the station distributed to low energy grid of P2D.",
    LegoBuild: "Required by MODule activities to power the module.",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "I10",
    Dep2: "I16",
    Dep3: "I19",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "y",
    Ctrl_type: "Int-lpwr.png ",
    Ctrl_num: 50,
    InitiativeColor: "#ffff00",
    "ini-logo": "I-logo.png",
    NeedInt: "",
    sfondo: "bg20"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L01",
    Title: "Air conditioning compressor",
    Complexity: 2,
    Defense: 0,
    Supremacy: 0,
    Notes: "Massive plant for recycling air and distributing it back to all rooms where people is living.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "I04",
    Dep2: "I12",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yy",
    sfondo: "bg1"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L02",
    Title: "Air conditioning fan (Design)",
    Complexity: 3,
    Defense: 0,
    Supremacy: 0,
    Notes: "Design of the fans to be installed in each component to connect this to the central air conditioning piping.<br>Designed for mass production.",
    LegoBuild: "Required by LIVing modules. Design and build 1 but we need many.",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "L01",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "",
    sfondo: "bg2"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L03",
    Title: "20x Air conditioning fans",
    Complexity: 5,
    Defense: 0,
    Supremacy: 0,
    Notes: "Fans to connect each component to the central air conditioning piping. ",
    LegoBuild: "Required by LIVing modules.",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "L02",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "Int-liv.png ",
    Ctrl_num: 20,
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "",
    sfondo: "bg3"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L04",
    Title: "Water tank",
    Complexity: 1,
    Defense: 0,
    Supremacy: 0,
    Notes: "Store water for the needs of the station.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yy",
    sfondo: "bg4"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L05",
    Title: "Medical lab",
    Complexity: 8,
    Defense: 1,
    Supremacy: 0,
    Notes: "Room for taking care of humans living the station. It has 3 beds for care and analysisCOMMA 3 robotic bio-analysersCOMMA and different boards for drugs and medicines.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "L20",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yyy",
    sfondo: "bg5"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L06",
    Title: "Dormitory for Troopers",
    Complexity: 3,
    Defense: 1,
    Supremacy: 0,
    Notes: "Restroom for a platoon of 6 Space Troopers.",
    LegoBuild: "For a platoon of 6 stormtroopers",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "L07",
    Dep2: "L12",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yyy",
    sfondo: "bg6"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L07",
    Title: "Lavatories",
    Complexity: 2,
    Defense: 0,
    Supremacy: 0,
    Notes: "Lavatories close to a room for 6 Space Troopers.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "L04",
    Dep2: "L11",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yyy",
    sfondo: "bg7"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L08",
    Title: "Dormitory for officer",
    Complexity: 3,
    Defense: 1,
    Supremacy: 1,
    Notes: "Restroom for an officer of the Space Troopers.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "L07",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yyy",
    sfondo: "bg8"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L09",
    Title: "2x Troopers facilities",
    Complexity: 8,
    Defense: 1,
    Supremacy: 1,
    Notes: "Facilities for 2 platoons of 6 Space Troopers (restrooms with lavatories)",
    LegoBuild: "For 2 platoons of 6 stormtroopers",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "L06",
    Dep2: "L19",
    Dep3: "L20",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "y",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yyy",
    sfondo: "bg9"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L10",
    Title: "Gran Koenig’s room",
    Complexity: 5,
    Defense: 0,
    Supremacy: 1,
    Notes: "Room with the special black octagonal cocoon to recharge Gran Koening’s cyborg armour.<br>The lid has automatic device to open the cocoon.",
    LegoBuild: "With his special black octagonal cocoon for resting",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "L20",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yyy",
    sfondo: "bg10"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L11",
    Title: "Garbage system",
    Complexity: 2,
    Defense: 0,
    Supremacy: 0,
    Notes: "Plant to collect trash coming from rooms of the station.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yy",
    sfondo: "bg11"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L12",
    Title: "Garbage compactor #1",
    Complexity: 1,
    Defense: 0,
    Supremacy: 0,
    Notes: "Double press for compacting trash operating every 12 hours.<br>It has a door for inspection with magnetic protection.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "y",
    Dep1: "L11",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yyyy",
    sfondo: "bg12"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L13",
    Title: "2x Troopers facilities",
    Complexity: 8,
    Defense: 1,
    Supremacy: 1,
    Notes: "Facilities for 2 platoons of 6 Space Troopers (restrooms with lavatories)",
    LegoBuild: "For 2 platoons of 6 stormtroopers",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "L06",
    Dep2: "L20",
    Dep3: "D11",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "y",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yyy",
    sfondo: "bg13"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L14",
    Title: "Cafeteria",
    Complexity: 5,
    Defense: 0,
    Supremacy: 0,
    Notes: "Rest area to manage meal for 12 people taking food from an automatic distributor.",
    LegoBuild: "For 12 persons",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "L07",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yyy",
    sfondo: "bg14"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L15",
    Title: "Game arena",
    Complexity: 5,
    Defense: 0,
    Supremacy: 0,
    Notes: "Area for the Ball game where spectators can assist the game. <br>This game is similar to basket where 2 teams of 3 players play a zero gravity.",
    LegoBuild: "For 3 vs 3 players",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yyy",
    sfondo: "bg15"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L16",
    Title: "2x Troopers facilities",
    Complexity: 8,
    Defense: 1,
    Supremacy: 1,
    Notes: "Facilities for 2 platoons of 6 Space Troopers (restrooms with lavatories)",
    LegoBuild: "For 2 platoons of 6 stormtroopers",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "L06",
    Dep2: "L19",
    Dep3: "L20",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "y",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yyy",
    sfondo: "bg16"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L17",
    Title: "Garbage compactor #2",
    Complexity: 1,
    Defense: 0,
    Supremacy: 0,
    Notes: "Double press for compacting trash operating every 12 hours.<br>It has a door for inspection with magnetic protection.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "y",
    Dep1: "L12",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yyyy",
    sfondo: "bg17"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L18",
    Title: "30x Air conditioning fans",
    Complexity: 8,
    Defense: 0,
    Supremacy: 0,
    Notes: "Fans to connect each component to the central air conditioning piping. ",
    LegoBuild: "Required by LIVing modules.",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "L02",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "Int-liv.png",
    Ctrl_num: 30,
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "",
    sfondo: "bg18"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L19",
    Title: "Secondary compressor",
    Complexity: 2,
    Defense: 0,
    Supremacy: 0,
    Notes: "Redundant device for the main air compressor for the conditioning system. ",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "L01",
    Dep2: "I15",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yy",
    sfondo: "bg19"
  },
  {
    NumCards: 1,
    Epic: "Living",
    Card_ID: "L20",
    Title: "Artificial gravity system",
    Complexity: 5,
    Defense: 0,
    Supremacy: 0,
    Notes: "Rockets to spin the rotating momentum of the stationCOMMA creating the centrifugal effect of gravity.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "",
    Dec: "y",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#00ff00",
    "ini-logo": "L-logo.png",
    NeedInt: "yy",
    sfondo: "bg20"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S01",
    Title: "Planet destroyer",
    Complexity: 13,
    Defense: 1,
    Supremacy: 8,
    Notes: "Wide parabola with a collider of 6 super-lasers. To work at full power needs to be connected to 3 P2Ds.",
    LegoBuild: "Build: 4 connection to power generatorCOMMA connected to 2 Decouplers",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "y",
    Dep1: "I14",
    Dep2: "I08",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "yyy",
    sfondo: "bg1"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S02",
    Title: "Emperor throne room",
    Complexity: 5,
    Defense: 0,
    Supremacy: 2,
    Notes: "Round shaped room where the Emperor meet Grand Koenigs (and other subjectsCOMMA sometimes...).",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "D10",
    Dep2: "L20",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "yyy",
    sfondo: "bg2"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S03",
    Title: "Torture room",
    Complexity: 3,
    Defense: 0,
    Supremacy: 3,
    Notes: "Room where prisoners are tortured.<br>It has 1 iron bed with different horrible devices around it.",
    LegoBuild: "Build: close to cell block",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "S08",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "yyy",
    sfondo: "bg3"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S04",
    Title: "The balcony of terror",
    Complexity: 2,
    Defense: 0,
    Supremacy: 2,
    Notes: "Close to throne roomCOMMA it has a wide screened window facing near the parabola of the planet destroyer. ",
    LegoBuild: "Build: with a wide window on the spaceCOMMA close Superlaser",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "S01",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "yyy",
    sfondo: "bg4"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S05",
    Title: "Space fighter (Design)",
    Complexity: 3,
    Defense: 2,
    Supremacy: 2,
    Notes: "The short range attack vehicle of the fleet for a single pilot. Equipped with 2 lateral wigs to use solar windCOMMA a spherical cabin and a single directional pulse engine.",
    LegoBuild: "We need many. Build: Design minifig and build microfig scale (> 8 pieces).",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "T03",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "",
    sfondo: "bg5"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S06",
    Title: "Black squadron",
    Complexity: 5,
    Defense: 2,
    Supremacy: 5,
    Notes: "The basic team of 5 space fighters with patrol and attack capabilities.",
    LegoBuild: "5 tie fighters Build: microfig scale",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "S05",
    Dep2: "T21",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "",
    sfondo: "bg6"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S07",
    Title: "Block for 3+3 cells",
    Complexity: 3,
    Defense: 0,
    Supremacy: 0,
    Notes: "A corridor to connect 6 prison cells closed with a large vertical door for security reasons. On one entrance side there is a circular control panel with all controlsCOMMA on the opposite there is the entrance to the torture room. ",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "L11",
    Dep2: "I09",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "yyy",
    sfondo: "bg7"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S08",
    Title: "Prison cell",
    Complexity: 1,
    Defense: 0,
    Supremacy: 1,
    Notes: "A cell for one single prisoner. Only 1 bed and 1 door entering in the cell block towards 3 steps.",
    LegoBuild: "For 1 single prisoner",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "S07",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "yyy",
    sfondo: "bg8"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S09",
    Title: "2x prison cells",
    Complexity: 2,
    Defense: 1,
    Supremacy: 1,
    Notes: "2 cells for single prisoners. Each cell has 1 bed and 1 door entering in the cell block towards 3 steps.",
    LegoBuild: "In the cell block",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "S08",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "yyy",
    sfondo: "bg9"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S10",
    Title: "Red squadron",
    Complexity: 5,
    Defense: 2,
    Supremacy: 2,
    Notes: "The basic team of 5 space fighters with patrol and attack capabilities.",
    LegoBuild: "5 tie fighters Build: microfig scale",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "S06",
    Dep2: "T15",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "",
    sfondo: "bg10"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S11",
    Title: "Space bomber (Design)",
    Complexity: 2,
    Defense: 1,
    Supremacy: 3,
    Notes: "Designed for bombing cities on planetsCOMMA or other spaceships. With a cabin for 2 pilotsCOMMA a bay for for weaponsCOMMA it has a dual pulse engine on the back of the central element and 2 large gravitational stabilizers on the sides.",
    LegoBuild: "We need many. Build: Design minifig and build microfig scale (> 8 pieces).",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "S05",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "",
    sfondo: "bg11"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S12",
    Title: "Blue squadron",
    Complexity: 5,
    Defense: 2,
    Supremacy: 2,
    Notes: "The basic team of 5 space bombers with heavy attack approach.",
    LegoBuild: "5 tie bombers Build: microfig scale",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "S11",
    Dep2: "T03",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "",
    sfondo: "bg12"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S13",
    Title: "Purple squadron",
    Complexity: 5,
    Defense: 2,
    Supremacy: 2,
    Notes: "The basic team of 5 space fighters with patrol and attack capabilities.",
    LegoBuild: "5 tie fighters Build: microfig scale",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "S06",
    Dep2: "T03",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "",
    sfondo: "bg13"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S14",
    Title: "3x single cells",
    Complexity: 2,
    Defense: 1,
    Supremacy: 1,
    Notes: "2 cells for single prisoners. Each cell has 1 bed and 1 door entering in the cell block towards 3 steps.",
    LegoBuild: "In the cell block",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "S08",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "yyy",
    sfondo: "bg14"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S15",
    Title: "Gold squadron",
    Complexity: 5,
    Defense: 2,
    Supremacy: 2,
    Notes: "The basic team of 5 space fighters with patrol and attack capabilities.",
    LegoBuild: "5 tie fighters Build: microfig scale",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "S06",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "",
    sfondo: "bg15"
  },
  {
    NumCards: 1,
    Epic: "Supremacy",
    Card_ID: "S16",
    Title: "Hyperspace Nullifier ",
    Complexity: 5,
    Defense: 1,
    Supremacy: 3,
    Notes: "High impulse electro-magnetic beamer that can distort HyperspaceCOMMA creating black holes and capture every vehicle in transit.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "",
    Dec: "y",
    Dep1: "C15",
    Dep2: "D06",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff00ff",
    "ini-logo": "S-logo.png",
    NeedInt: "yy",
    sfondo: "bg16"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T01",
    Title: "WARP engine",
    Complexity: 13,
    Defense: 0,
    Supremacy: 1,
    Notes: "It uses amplified energy to excite molecules of Lithium crystals that generates high speed ionic particles able to move the station in the hyperspace.",
    LegoBuild: "Build: >100 pieces and with moving parts",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "y",
    Dep1: "I01",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yyy",
    sfondo: "bg1"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T02",
    Title: "Landing bay deck #1",
    Complexity: 3,
    Defense: 0,
    Supremacy: 0,
    Notes: "Wide area to let large and small vehicles land. It has some spaces on both sides for temporary parking and eventually downloading goods.",
    LegoBuild: "1 per landing bay",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "T03",
    Dep2: "T20",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yyy",
    sfondo: "bg2"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T03",
    Title: "Landing bay #1",
    Complexity: 5,
    Defense: 1,
    Supremacy: 1,
    Notes: "Wide area to let large and small vehicles land. It has some spaces on both sides for temporary parking and eventually downloading goods.",
    LegoBuild: "To connect landing bays",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "T02",
    Dep2: "T04",
    Dep3: "L20",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yyy",
    sfondo: "bg3"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T04",
    Title: "Tractor beam",
    Complexity: 1,
    Defense: 2,
    Supremacy: 2,
    Notes: "Directional field force to guide vehicles into the landing bay. Requires to be connected directly to the main source of energy.",
    LegoBuild: "1 per landing bay",
    Liv: "",
    Com: "y",
    Pwr: "",
    Dec: "y",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yy",
    sfondo: "bg4"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T05",
    Title: "Vehicle recharger",
    Complexity: 1,
    Defense: 0,
    Supremacy: 0,
    Notes: "To inject energy into the vehicle batteries to be used for impulse engines.<br>Can recharge 2 vehicles at the same moment.",
    LegoBuild: "",
    Liv: "",
    Com: "y",
    Pwr: "y",
    Dec: "y",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yyy",
    sfondo: "bg5"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T06",
    Title: "Warehouse",
    Complexity: 1,
    Defense: 0,
    Supremacy: 0,
    Notes: "Room to store goods just downloaded from ships.2 doors one on the landing bay and the other into the stationCOMMA both require a coding key.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "T05",
    Dep2: "T10",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yyy",
    sfondo: "bg6"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T07",
    Title: "2x Hypertrain stops",
    Complexity: 8,
    Defense: 1,
    Supremacy: 0,
    Notes: "HyperTrain stop to let people coming in and out. It has vacuum safe doors to isolate the railways in the vacuum tube.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "T17",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yyy",
    sfondo: "bg7"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T08",
    Title: "Hypertrain",
    Complexity: 5,
    Defense: 0,
    Supremacy: 0,
    Notes: "A super fast transport for up to 30 troopers or equivalent weight in goods.<br>It is moving into a single 8 shaped loop tube touching all critical areas of the station.",
    LegoBuild: "Build: microfig scale for 30 figs",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "y",
    Dep1: "T07",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "y",
    sfondo: "bg8"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T09",
    Title: "Imperial shuttle",
    Complexity: 3,
    Defense: 0,
    Supremacy: 2,
    Notes: "The vehicle for personal mobility of KoenigsCOMMA with the capability to jump directly in Hyperspace.",
    LegoBuild: "",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "T3",
    Dep2: "L14",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "",
    sfondo: "bg9"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T10",
    Title: "Galileo shuttle",
    Complexity: 2,
    Defense: 0,
    Supremacy: 0,
    Notes: "This short range shuttle to connect the different landing bays and move quickly people or goods.",
    LegoBuild: "To connect landing bays",
    Liv: "",
    Com: "",
    Pwr: "",
    Dec: "",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "",
    sfondo: "bg10"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T11",
    Title: "2x Hypertrain stops",
    Complexity: 5,
    Defense: 1,
    Supremacy: 0,
    Notes: "Hypertrain’s stop to let people coming in and out. It has vacuum safe doors to isolate the railways in the vacuum tube.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "T08",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yyy",
    sfondo: "bg11"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T12",
    Title: "Landing bay deck #3",
    Complexity: 3,
    Defense: 1,
    Supremacy: 1,
    Notes: "Wide area to let large and small vehicles land. It has some spaces on both sides for temporary parking and eventually downloading goods.",
    LegoBuild: "1 per landing bay",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "T13",
    Dep2: "T14",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yyy",
    sfondo: "bg12"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T13",
    Title: "Landing bay #3",
    Complexity: 5,
    Defense: 1,
    Supremacy: 1,
    Notes: "Wide area to let large and small vehicles land. It has some spaces on both sides for temporary parking and eventually downloading goods.",
    LegoBuild: "To connect landing bays",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "T14",
    Dep2: "T20",
    Dep3: "L20",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yyy",
    sfondo: "bg13"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T14",
    Title: "Tractor beam",
    Complexity: 1,
    Defense: 1,
    Supremacy: 2,
    Notes: "To drive vehicles into the landing bay from approaching to landing. If needed beam can force vehicle to land in a controlled way.",
    LegoBuild: "1 per landing bay",
    Liv: "",
    Com: "y",
    Pwr: "",
    Dec: "y",
    Dep1: "T04",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yy",
    sfondo: "bg14"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T15",
    Title: "2x Hypertrain stops",
    Complexity: 8,
    Defense: 1,
    Supremacy: 0,
    Notes: "Hypertrain’s stop to let people coming in and out. It has vacuum safe doors to isolate the railways in the vacuum tube.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yyy",
    sfondo: "bg15"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T16",
    Title: "3x internal elevators",
    Complexity: 2,
    Defense: 1,
    Supremacy: 0,
    Notes: "Each elevator can bring up to 5 people or equivalent goods. They have special engines to move vertically and horizontally.",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "T17",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yyy",
    sfondo: "bg16"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T17",
    Title: "6x elevators stops",
    Complexity: 5,
    Defense: 1,
    Supremacy: 0,
    Notes: "Placed in the centre of the main corridors of the stationCOMMA with a small waiting area. ",
    LegoBuild: "",
    Liv: "y",
    Com: "y",
    Pwr: "",
    Dec: "y",
    Dep1: "L20",
    Dep2: "",
    Dep3: "",
    DepInt1: "",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yyy",
    sfondo: "bg17"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T18",
    Title: "Landing bay deck #2",
    Complexity: 3,
    Defense: 1,
    Supremacy: 1,
    Notes: "The control room that supervises all activities in the landing deck. 5 traffic control experts manage all activities from landing to taking off and vehicle identification.",
    LegoBuild: "1 per landing bay",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "T04",
    Dep2: "T19",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yyy",
    sfondo: "bg18"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T19",
    Title: "Landing bay #2",
    Complexity: 5,
    Defense: 1,
    Supremacy: 1,
    Notes: "Wide area to let large and small vehicles land. It has some spaces on both sides for temporary parking and eventually downloading goods.",
    LegoBuild: "To connect landing bays",
    Liv: "y",
    Com: "y",
    Pwr: "y",
    Dec: "",
    Dep1: "T14",
    Dep2: "T16",
    Dep3: "L20",
    DepInt1: "y",
    DepInt2: "y",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yyy",
    sfondo: "bg19"
  },
  {
    NumCards: 1,
    Epic: "Transport",
    Card_ID: "T20",
    Title: "Tractor beam",
    Complexity: 1,
    Defense: 1,
    Supremacy: 2,
    Notes: "Directional field force to guide vehicles into the landing bay. Requires to be connected directly to the main source of energy.",
    LegoBuild: "1 per landing bay",
    Liv: "",
    Com: "y",
    Pwr: "",
    Dec: "y",
    Dep1: "T04",
    Dep2: "",
    Dep3: "",
    DepInt1: "y",
    DepInt2: "",
    DepInt3: "",
    Ctrl_type: "",
    Ctrl_num: "",
    InitiativeColor: "#ff0000",
    "ini-logo": "T-logo.png",
    NeedInt: "yy",
    sfondo: "bg20"
  }
]

module.exports = {

  new: function() {
    return backlog
  }
}
